[package]
name = "gitgui"
version = "0.1.6"
edition = "2021"

[dependencies]
egui = { version = "=0.36.1", default-features = false, features = ["default_fonts"] }
epaint = { version = "=0.36.1", default-features = false }
libc = "0.2"
base64 = "0.22"
flate2 = "1"
anyhow = "1"
git2 = { version = "=0.21.0", default-features = false }
png = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
smallvec = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
