# Generated by scripts/formula.py from the release assets. Do not edit by hand.
#
#   brew tap antonellof/gitgui https://github.com/antonellof/gitgui
#   brew install antonellof/gitgui/gitgui
class Gitgui < Formula
  desc "Pixel-rendered git GUI for kitty-graphics terminals"
  homepage "https://github.com/antonellof/gitgui"
  version "0.8.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.2/gitgui-0.8.2-macos-arm64.tar.gz"
      sha256 "62e3b4e664b5ce9459bbcd2d8f4e4857779e2d8e0554a7b029ab9dff89fe7b3e"
    end
    on_intel do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.2/gitgui-0.8.2-macos-x86_64.tar.gz"
      sha256 "1d9b7e996be31828ecaad683370a0c399ce97f76fd017f1a2676e05e328d2675"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.2/gitgui-0.8.2-linux-arm64.tar.gz"
      sha256 "0b2247b017504ac425c4df4819b7fb1de1ef97e0a8c8da380b32859afb505635"
    end
    on_intel do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.2/gitgui-0.8.2-linux-x86_64.tar.gz"
      sha256 "239f7ec7532a9296d8a82f533e98055e8467ace0b90d47cf7e6a02be458df59b"
    end
  end

  def install
    # Each tarball holds one file, gitgui-<version>-<platform>.
    bin.install Dir["gitgui-*"].first => "gitgui"
  end

  def caveats
    <<~EOS
      In-terminal rendering needs a kitty-graphics terminal (cmux, Ghostty,
      kitty, WezTerm); anywhere else gitgui opens a desktop window.
      Check this terminal with: gitgui --probe
    EOS
  end

  test do
    # No terminal in the test sandbox, so drive the modes that need none:
    # the agent listing, and one rendered frame of an empty repository.
    assert_match "[", shell_output("#{bin}/gitgui ls")
    system "git", "init", "-q", testpath/"repo"
    system bin/"gitgui", "--headless-frame", testpath/"frame.png",
                         "--repo", testpath/"repo", "--size", "400x300"
    assert_path_exists testpath/"frame.png"
  end
end
