# Generated by scripts/formula.py from the release assets. Do not edit by hand.
#
#   brew tap antonellof/gitgui https://github.com/antonellof/gitgui
#   brew install antonellof/gitgui/gitgui
class Gitgui < Formula
  desc "Pixel-rendered git GUI for kitty-graphics terminals"
  homepage "https://github.com/antonellof/gitgui"
  version "0.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.0/gitgui-0.8.0-macos-arm64.tar.gz"
      sha256 "4e42e023f0728a9cfad5851dfcd9ee65726f563835c9a58a5dcb7ed4adb350f3"
    end
    on_intel do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.0/gitgui-0.8.0-macos-x86_64.tar.gz"
      sha256 "d0ff6b461447ac74a46413dc1662fa21be4cb521621b81e6179077fb696549c6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.0/gitgui-0.8.0-linux-arm64.tar.gz"
      sha256 "dedcb02d3d4e3c71220b0d51b6ad4511a0b2e6260b1edd078d77fec5d2196bfd"
    end
    on_intel do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.0/gitgui-0.8.0-linux-x86_64.tar.gz"
      sha256 "ee92d1c34cc118480a18f278517a5b832319d11b0ca3b70268089ae8232353f1"
    end
  end

  def install
    # Each tarball holds one file, gitgui-<version>-<platform>.
    bin.install Dir["gitgui-*"].first => "gitgui"
  end

  def caveats
    <<~EOS
      In-terminal rendering needs a kitty-graphics terminal (cmux, Ghostty,
      kitty, WezTerm); anywhere else gitgui opens a desktop window.
      Check this terminal with: gitgui --probe
    EOS
  end

  test do
    # No terminal in the test sandbox, so drive the modes that need none:
    # the agent listing, and one rendered frame of an empty repository.
    assert_match "[", shell_output("#{bin}/gitgui ls")
    system "git", "init", "-q", testpath/"repo"
    system bin/"gitgui", "--headless-frame", testpath/"frame.png",
                         "--repo", testpath/"repo", "--size", "400x300"
    assert_path_exists testpath/"frame.png"
  end
end
