# Generated by scripts/formula.py from the release assets. Do not edit by hand.
#
#   brew tap antonellof/gitgui https://github.com/antonellof/gitgui
#   brew install antonellof/gitgui/gitgui
class Gitgui < Formula
  desc "Pixel-rendered git GUI for kitty-graphics terminals"
  homepage "https://github.com/antonellof/gitgui"
  version "0.8.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.1/gitgui-0.8.1-macos-arm64.tar.gz"
      sha256 "6ae3ffd4be1e2be8101a3123ce94d514007151b5fed76fd6ac72e33e860ce384"
    end
    on_intel do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.1/gitgui-0.8.1-macos-x86_64.tar.gz"
      sha256 "8be450cb33be10ec7355740fa98554fa036b319a011f302750b76a213efabca7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.1/gitgui-0.8.1-linux-arm64.tar.gz"
      sha256 "4e355f3a671fd8b7b71595e8086210aaadb09c7eb0946a13b7c63a4de4eaa205"
    end
    on_intel do
      url "https://github.com/antonellof/gitgui/releases/download/v0.8.1/gitgui-0.8.1-linux-x86_64.tar.gz"
      sha256 "5537f5b188a16296f59598a275f8b8a09a15efbbbb644945d600256ef4285714"
    end
  end

  def install
    # Each tarball holds one file, gitgui-<version>-<platform>.
    bin.install Dir["gitgui-*"].first => "gitgui"
  end

  def caveats
    <<~EOS
      In-terminal rendering needs a kitty-graphics terminal (cmux, Ghostty,
      kitty, WezTerm); anywhere else gitgui opens a desktop window.
      Check this terminal with: gitgui --probe
    EOS
  end

  test do
    # No terminal in the test sandbox, so drive the modes that need none:
    # the agent listing, and one rendered frame of an empty repository.
    assert_match "[", shell_output("#{bin}/gitgui ls")
    system "git", "init", "-q", testpath/"repo"
    system bin/"gitgui", "--headless-frame", testpath/"frame.png",
                         "--repo", testpath/"repo", "--size", "400x300"
    assert_path_exists testpath/"frame.png"
  end
end
