#!/usr/bin/env python3
"""Regenerate Formula/gitgui.rb from the assets of a published release.

The sha256 of each asset comes from the GitHub API (the `digest` field), so
nothing is downloaded.

    python3 scripts/formula.py            # the newest release
    python3 scripts/formula.py 0.8.0      # a specific version

GITHUB_TOKEN is used when set (CI rate limits), otherwise anonymous.
"""

import json
import os
import sys
import urllib.request

REPO = os.environ.get("GITGUI_REPO", "antonellof/gitgui")
OUT = os.environ.get("GITGUI_FORMULA", "Formula/gitgui.rb")
# The four platforms the release workflow builds.
PLATFORMS = ["macos-arm64", "macos-x86_64", "linux-arm64", "linux-x86_64"]

TEMPLATE = '''\
# Generated by scripts/formula.py from the release assets. Do not edit by hand.
#
#   brew tap antonellof/gitgui https://github.com/{repo}
#   brew install antonellof/gitgui/gitgui
class Gitgui < Formula
  desc "Pixel-rendered git GUI for kitty-graphics terminals"
  homepage "https://github.com/{repo}"
  version "{version}"
  license "MIT"

  on_macos do
    on_arm do
{macos_arm}
    end
    on_intel do
{macos_intel}
    end
  end

  on_linux do
    on_arm do
{linux_arm}
    end
    on_intel do
{linux_intel}
    end
  end

  def install
    # Each tarball holds one file, gitgui-<version>-<platform>.
    bin.install Dir["gitgui-*"].first => "gitgui"
  end

  def caveats
    <<~EOS
      In-terminal rendering needs a kitty-graphics terminal (cmux, Ghostty,
      kitty, WezTerm); anywhere else gitgui opens a desktop window.
      Check this terminal with: gitgui --probe
    EOS
  end

  test do
    # No terminal in the test sandbox, so drive the modes that need none:
    # the agent listing, and one rendered frame of an empty repository.
    assert_match "[", shell_output("#{{bin}}/gitgui ls")
    system "git", "init", "-q", testpath/"repo"
    system bin/"gitgui", "--headless-frame", testpath/"frame.png",
                         "--repo", testpath/"repo", "--size", "400x300"
    assert_path_exists testpath/"frame.png"
  end
end
'''


def fetch(url):
    request = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def assets_of(release):
    """{platform: (url, sha256)} for the four release tarballs."""
    version = release["tag_name"].lstrip("v")
    out = {}
    for asset in release.get("assets", []):
        for platform in PLATFORMS:
            if asset["name"] == f"gitgui-{version}-{platform}.tar.gz":
                digest = asset.get("digest", "")
                if not digest.startswith("sha256:"):
                    sys.exit(f"{asset['name']} carries no sha256 digest in the API")
                out[platform] = (asset["browser_download_url"], digest.split(":", 1)[1])
    missing = [p for p in PLATFORMS if p not in out]
    if missing:
        sys.exit(f"release {version} is missing assets: {', '.join(missing)}")
    return version, out


def block(assets, platform, indent=6):
    url, sha = assets[platform]
    pad = " " * indent
    return f'{pad}url "{url}"\n{pad}sha256 "{sha}"'


def main():
    version = sys.argv[1].lstrip("v") if len(sys.argv) > 1 else None
    url = (
        f"https://api.github.com/repos/{REPO}/releases/tags/v{version}"
        if version
        else f"https://api.github.com/repos/{REPO}/releases/latest"
    )
    version, assets = assets_of(fetch(url))
    text = TEMPLATE.format(
        repo=REPO,
        version=version,
        macos_arm=block(assets, "macos-arm64"),
        macos_intel=block(assets, "macos-x86_64"),
        linux_arm=block(assets, "linux-arm64"),
        linux_intel=block(assets, "linux-x86_64"),
    )
    os.makedirs(os.path.dirname(OUT) or ".", exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT} for {version}")


if __name__ == "__main__":
    main()
